export const AUTH = 'AUTH';
export const GET_SLIDES = 'GET_SLIDES';
export const GET_WEEKLY_NEWS = 'GET_WEEKLY_NEWS';
export const TOGGLE_WEEKLY_NEWS_POPUP = 'TOGGLE_WEEKLY_NEWS_POPUP';
export const RES_TOKEN = 'RESTORE_TOKEN';
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
export const FORM_SUBMIT_FAILED = 'FORM_SUBMIT_FAILED';

export const CREATE_REPO_REQUEST = 'CREATE_REPO_REQUEST'
export const CREATE_REPO_SUCCESS = 'CREATE_REPO_SUCCESS'
export const CREATE_REPO_FAIL = 'CREATE_REPO_FAIL'
export const CREATE_REPO_RESET = 'CREATE_REPO_RESET'

export const DELETE_REPO_REQUEST = 'DELETE_REPO_REQUEST'
export const DELETE_REPO_SUCCESS = 'DELETE_REPO_SUCCESS'
export const DELETE_REPO_FAIL = 'DELETE_REPO_FAIL'
export const DELETE_REPO_RESET = 'DELETE_REPO_RESET'

export const REPO_CONTENT_REQUEST = 'REPO_CONTENT_REQUEST'
export const REPO_CONTENT_SUCCESS = 'REPO_CONTENT_SUCCESS'
export const REPO_CONTENT_FAIL = 'REPO_CONTENT_FAIL'
export const REPO_CONTENT_RESET = 'REPO_CONTENT_RESET'

export const SAVE_REPO_REQUEST = 'SAVE_REPO_REQUEST'
export const SAVE_REPO_SUCCESS = 'SAVE_REPO_SUCCESS'
export const SAVE_REPO_FAIL = 'SAVE_REPO_FAIL'
export const SAVE_REPO_RESET = 'SAVE_REPO_RESET'

export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST'
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS'
export const IMAGE_UPLOAD_FAIL = 'IMAGE_UPLOAD_FAIL'
export const IMAGE_UPLOAD_RESET = 'IMAGE_UPLOAD_RESET'

export const POST_REPO_REQUEST = 'POST_REPO_REQUEST'
export const POST_REPO_SUCCESS = 'POST_REPO_SUCCESS'
export const POST_REPO_FAIL = 'POST_REPO_FAIL'
export const POST_REPO_RESET = 'POST_REPO_RESET'

export const REPO_LIST_REQUEST = 'REPO_LIST_REQUEST'
export const REPO_LIST_SUCCESS = 'REPO_LIST_SUCCESS'
export const REPO_LIST_FAIL = 'REPO_LIST_FAIL'
export const REPO_LIST_RESET = 'REPO_LIST_RESET'