export const AUTH = 'AUTH';
export const GET_SLIDES = 'GET_SLIDES';
export const GET_WEEKLY_NEWS = 'GET_WEEKLY_NEWS';
export const TOGGLE_WEEKLY_NEWS_POPUP = 'TOGGLE_WEEKLY_NEWS_POPUP';
export const RES_TOKEN = 'RESTORE_TOKEN';
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
export const FORM_SUBMIT_FAILED = 'FORM_SUBMIT_FAILED';

export const CREATE_DRAFT_REQUEST = 'CREATE_DRAFT_REQUEST'
export const CREATE_DRAFT_SUCCESS = 'CREATE_DRAFT_SUCCESS'
export const CREATE_DRAFT_FAIL = 'CREATE_DRAFT_FAIL'

export const DRAFTS_LIST_REQUEST = 'DRAFTS_LIST_REQUEST'
export const DRAFTS_LIST_SUCCESS = 'DRAFTS_LIST_SUCCESS'
export const DRAFTS_LIST_ERROR = 'DRAFTS_LIST_ERROR'