export const AUTH = 'AUTH';
export const GET_SLIDES = 'GET_SLIDES';
export const GET_WEEKLY_NEWS = 'GET_WEEKLY_NEWS';
export const TOGGLE_WEEKLY_NEWS_POPUP = 'TOGGLE_WEEKLY_NEWS_POPUP';
export const RES_TOKEN = 'RESTORE_TOKEN';
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
export const FORM_SUBMIT_FAILED = 'FORM_SUBMIT_FAILED';

export const CREATE_REPO_REQUEST = 'CREATE_REPO_REQUEST'
export const CREATE_REPO_SUCCESS = 'CREATE_REPO_SUCCESS'
export const CREATE_REPO_FAIL = 'CREATE_REPO_FAIL'
export const CREATE_REPO_RESET = 'CREATE_REPO_RESET'

export const DRAFTS_LIST_REQUEST = 'DRAFTS_LIST_REQUEST'
export const DRAFTS_LIST_SUCCESS = 'DRAFTS_LIST_SUCCESS'
export const DRAFTS_LIST_ERROR = 'DRAFTS_LIST_ERROR'

export const DELETE_REPO_REQUEST = 'DELETE_REPO_REQUEST'
export const DELETE_REPO_SUCCESS = 'DELETE_REPO_SUCCESS'
export const DELETE_REPO_FAIL = 'DELETE_REPO_FAIL'
export const DELETE_REPO_RESET = 'DELETE_REPO_RESET'

export const DRAFT_CONTENT_REQUEST = 'DRAFT_CONTENT_REQUEST'
export const DRAFT_CONTENT_SUCCESS = 'DRAFT_CONTENT_SUCCESS'
export const DRAFT_CONTENT_FAIL = 'DRAFT_CONTENT_FAIL'
export const DRAFT_CONTENT_RESET = 'DRAFT_CONTENT_RESET'

export const SAVE_DRAFT_REQUEST = 'SAVE_DRAFT_REQUEST'
export const SAVE_DRAFT_SUCCESS = 'SAVE_DRAFT_SUCCESS'
export const SAVE_DRAFT_FAIL = 'SAVE_DRAFT_FAIL'
export const SAVE_DRAFT_RESET = 'SAVE_DRAFT_RESET'

export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST'
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS'
export const IMAGE_UPLOAD_FAIL = 'IMAGE_UPLOAD_FAIL'
export const IMAGE_UPLOAD_RESET = 'IMAGE_UPLOAD_RESET'

export const POST_ARTICLE_REQUEST = 'POST_ARTICLE_REQUEST'
export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS'
export const POST_ARTICLE_FAIL = 'POST_ARTICLE_FAIL'
export const POST_ARTICLE_RESET = 'POST_ARTICLE_RESET'

export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_RESET = 'GET_ARTICLES_RESET'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAIL = 'GET_ARTICLES_FAIL'

export const ARTICLE_CONTENT_REQUEST = 'ARTICLE_CONTENT_REQUEST'
export const ARTICLE_CONTENT_SUCCESS = 'ARTICLE_CONTENT_SUCCESS'
export const ARTICLE_CONTENT_FAIL = 'ARTICLE_CONTENT_FAIL'

export const REPO_LIST_REQUEST = 'REPO_LIST_REQUEST'
export const REPO_LIST_SUCCESS = 'REPO_LIST_SUCCESS'
export const REPO_LIST_FAIL = 'REPO_LIST_FAIL'
export const REPO_LIST_RESET = 'REPO_LIST_RESET'